project:
  type: website
  output-dir: docs

website:
  title: "olleholt.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources

format:
  html:
    theme:
      light: vapor
      dark: vapor
    css: styles.css
    toc: true

editor: visual

