project:
  type: website
  output-dir: docs

website:
  title: "olleholt.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blogs.qmd
        text: Blog
      - href: resources.qmd
        text: Resources
        title: false

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true

editor: visual

